### PR TITLE
Feature extent from the DB

### PR DESCRIPTION
**Pull request by chelm**
This is a minor version bump since it adds a new method that will eventually be used in Feature Service calls from koop's core BaseController

### CODE REVIEW

**Comment by ungoldman** [comment]
@chelm this looks good. is it alright if we bump to 1.0.0 to deal with the semver issue? see https://github.com/koopjs/koopjs.github.io/issues/6 for details

**Comment by chelm** [comment]
Sure, @ngoldman, I actually think it make sense as this repo has now matured to a point where I think all the features it likely have for a while are in.

**Comment by chelm** [comment]
@ngoldman made it v1.0.0

**Comment by ungoldman** [comment]
@chelm thanks dude. will merge/publish/release

**Pull request merged**
