### PR TITLE
Use geometry type in the DB

### PR DESCRIPTION
**Pull request by dmfenton**
This PR merges in @peacenlove's work. It uses geometry types in the database instead of casting from geojson

### CODE REVIEW

**Comment by dmfenton** [comment]
cc @koopjs/dev

**Comment by ungoldman** [comment]
Ideally you can cherry pick the commit or rebase off the branch and modify it so that they still receive credit for the contribution.

**Comment by dmfenton** [comment]
Yeah that's what I did (I checked out his branch anyways), but I guess it overwrote his commits when I merged locally. Weird.

**Comment by PeaceNlove** [comment]
Thanks :-)

**Comment by dmfenton** [comment]
I get what you're saying now. Would have helped it we had a test around this. Granted I did just snag your commits :stuck_out_tongue: 

We're going to have to migrate our data anyways due to jsonb. Still trying to figure out how that's going to work in practice.

**Comment by PeaceNlove** [comment]
:)
Jsonb looks interesting. Never heard of it until you mentioned it. I learned something as well tonight :)

**Pull request closed without merging**
