### PR TITLE
new version for applying coded domains plus a test for it

### PR DESCRIPTION
**Pull request by chelm**
Adds a new method called `applyCodedDomains` that scans each field (if present) and looks for matching values in field.domains

### CODE REVIEW

**Comment by chelm** [comment]
@ngoldman or @jgravois - take a peek? and merge when ready...

**Comment by chelm** [comment]
will publish to npm and create a new release post merge

**Comment by ungoldman** [comment]
@chelm looks OK to me. did you bump the version in `package.json` too?

**Comment by ungoldman** [comment]
See it now. Merging. Can I do a PR on this before we officially bump & release?

edit: I can't merge this, not a maintainer. ¯\_(ツ)_/¯

**Pull request merged**
